### ISSUE TITLE
Ненужный метод в BookStatus

### ISSUE THREAD

**Issue by Xini1** [skfl/andersen-task#10]
https://github.com/skfl/andersen-task/blob/main/src/main/java/com/andersentask/bookshop/book/enums/BookStatus.java#L14
Не вижу смысла в таком методе

**Comment by skfl** [comment]
Данный метод необходим для сортировки книг по их доступности в методе класса ```BookService```
https://github.com/skfl/andersen-task/blob/75173420bfb0fb5752e7add087bb0d82b3da03a4/src/main/java/com/andersentask/bookshop/book/services/BookService.java#L38

**Comment by Xini1** [comment]
Зачем создавать метод, который не делает ничего, кроме перенаправления вызова стандартному методу с похожим названием? Нельзя ли обойтись просто ordinal()?

**Comment by skfl** [comment]
Closed with PR https://github.com/skfl/andersen-task/pull/32
