### ISSUE TITLE
Статическая переменная в NoSuchBookException

### ISSUE THREAD

**Issue by Xini1** [skfl/andersen-task#11]
https://github.com/skfl/andersen-task/blob/main/src/main/java/com/andersentask/bookshop/book/exceptions/NoSuchBookException.java#L5
1) Принято писать private static final
2) Не вижу смысла в такой переменной, если она используется в единственном методе в том же классе. Почему бы не сделать просто:
`public NoSuchBookException(){
        super("No such book was found");
    }`

**Comment by skfl** [comment]
Class has been deleted. Closed
