### ISSUE TITLE
Возврат boolean из метода

### ISSUE THREAD

**Issue by Xini1** [skfl/andersen-task#16]
https://github.com/skfl/andersen-task/blob/main/src/main/java/com/andersentask/bookshop/user/facade/UserFacade.java#L32
Я бы сказал, что это не очень хорошая практика. В будущем у вас может появится третий случай завершения метода, а boolean может принимать только true либо false. Удобнее был бы Enum: SUCCESS, FAILURE, ADDITIONAL_ACTION_REQUIRED. Если думать об обратной совместимости, то лучше сразу возвращать enum, потом добавить туда новые значения проще, чем полностью поменять возвращаемое значение

**Comment by skfl** [comment]
Closed due class has been deleted
