### ISSUE TITLE
Привести репозиторий в приличный вид.

### ISSUE THREAD

**Issue by Xini1** [skfl/andersen-task#37]
Приведите код в проекте в единообразный вид: удалите неиспользуемый код (https://github.com/skfl/andersen-task/blob/main/src/main/java/com/andersentask/bookshop/order/service/OrderService.java), отформатируйте, удалите лишние пустые строки и т.п.

**Comment by skfl** [comment]
Done https://github.com/skfl/andersen-task/pull/56
