### ISSUE TITLE
Сортировка

### ISSUE THREAD

**Issue by Xini1** [skfl/andersen-task#38]
сортировать в самом приложении - это антипаттерн. как правило различные системы хранения умеют делать это лучше. Лучше отдать сортировку на откуп какой-нибудь базе данных
https://github.com/skfl/andersen-task/blob/main/src/main/java/com/andersentask/bookshop/book/services/BookService.java#L33

https://github.com/skfl/andersen-task/blob/main/src/main/java/com/andersentask/bookshop/order/service/OrderService.java#L68 - тоже относится

**Comment by skfl** [comment]
Согласен, а что тогда делать в случае когда БД отсутствует?

**Comment by ulad-sachkovski** [comment]
Как я понимаю, пока что методы сортировки должны быть просто в репозитории
когда появится БД, буим сортировать уже через запросы к БД

**Comment by Xini1** [comment]
Лучше сразу поправить интерфейс репозитория, добавить туда методы для получения уже отсортированных данных
